import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Swaroopa',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'john@mail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    
    {
      name: 'Praveen',
      email: 'pravs@mail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
    
    {
      name: 'Asher',
      email: 'asher@mail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
    
    {
      name: 'avisha',
      email: 'avi03@mail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
   products: [
      {
        // "id": "DmUr6q1EDYMC",
        name: "The Hitchhiker's Guide to the Galaxy",
        slug: 'the-hitchhikers-guide-to-the-galaxy',
        image: "http://books.google.com/books/content?id=DmUr6q1EDYMC&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE70YEM96JkOwhVjWNU45rXdsK78UbIl1SEQStIl-Xm6qfex5tu7IITG4EzOiYrvsDBlXrq7aZBLJlg-D4e-jwGkjONwpHFMpb4v3rFsfxEqFZFwWg2ouDVuYdbM8fORENVi92JhV&source=gbs_api", // 679px × 829px
        price: 5.50,
        countInStock: 10,
        rating: 4.5,
        numReviews: 10,
        description: "It's an ordinary Thursday lunchtime for Arthur Dent until his house gets demolished. The Earth follows shortly afterwards to make way for a new hyperspace express route, and his best friend has just announced that he's an alien. At this moment, they're hurtling through space with nothing but their towels and an innocuous-looking book inscribed, in large friendly letters, with the words: DON'T PANIC.",
      },
      {
        //"id": "_FdNjPxBETIC",
        name: 'The Shroud of Turin',
        slug: 'the-shroud-of-turin',
        image: "http://books.google.com/books/content?id=_FdNjPxBETIC&printsec=frontcover&img=1&zoom=5&imgtk=AFLRE73hJWr9GDfVjbkSdj3eTLy4IKsOdupWKQ9ID2b9-zNYmNZSjkXbKQZqgvfJeD7YLe6MwANUEwOwa3vWZ2gjoJlAmzDqR9qXlXH4puymWrw6z4LahvKwCuQN0CnDrc8UE1NcjnET&source=gbs_api",
        price: 10.30,
        countInStock: 0,
        rating: 4.0,
        numReviews: 10,
        description: "Rewritten and updated from Ian Wilson's original 1978 bestseller, The Turin Shroud.Two decades after radiocarbon dating declared the Turin Shroud a mediaeval fake, brand-new historical discoveries strongly suggest that this famous cloth, with its extraordinary photographic imprint, is genuinely Christ's shroud after all. In 1978 in his international bestseller The Turin Shroud Ian Wilson ignited worldwide public debate with his compelling case endorsing the shroud's authenticity. Now, 30 years later, he has completely rewritten and updated his earlier book to provide fresh evidence to support his original argument.",
      },
      {
        // "id": "A2ZErgEACAAJ",
        name: 'All The Light We Cannot See',
        slug: 'all-the-lights-we-cannot-see',
        image: "http://books.google.com/books/content?id=A2ZErgEACAAJ&printsec=frontcover&img=1&zoom=5&imgtk=AFLRE70QWQGGjBiWdYcDo3874PE72VXihSNNvc2GG5GJCIzFjF2hzWKRS5MWlQqkUkwGVtleeva7sMhR5HbHIPxQ30FVnLOXLP_IqDa1L6Sk8TVlj74Bsf2Nuz3enKUGYM6pcUyFU5Nr&source=gbs_api",
        price:  5.20,
        countInStock: 15,
        rating: 4.5,
        numReviews: 14,
        description: "WINNER OF THE 2015 PULITZER PRIZE FOR FICTIONNATIONAL BOOK AWARD FINALISTNEW YORK TIMES BESTSELLERWINNER OF THE CARNEGIE MEDAL FOR FICTION A beautiful, stunningly ambitious novel about a blind French girl and a German boy whose paths collide in occupied France as both try to survive the devastation of World War II 'Open your eyes and see what you can with them before they close forever.' For Marie-Laure, blind since the age of six, the world is full of mazes. The miniature of a Paris neighbourhood, made by her father to teach her the way home. The microscopic layers within the invaluable diamond that her father guards in the Museum of Natural History. "
      },
      {
        // "id": "XNktDwAAQBAJ",
        name: 'The Good Mothers',
        slug: 'the-good-mothers',
        image: "http://books.google.com/books/publisher/content?id=XNktDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE70c1z7NooNCARW8vzdWHI-bvHdBUfRiFUbRWwjuaWrQmXl702HM91qgGdv5DS_mkjfb4uHlg9Q9P72bI1MbxFmf6yJ4hToIlgmKqBFJipdufTXbAigunheVzAh41TSwrwkrHAmf&source=gbs_api",
        price: 8.80,
        countInStock: 5,
        rating: 4.5,
        numReviews: 10,
        description: "ou are born into it or marry in. Loyalty is absolute, bloodshed revered and you kill or go to your grave before betraying The Family. This code of omertà is how the 'Ndrangheta became the world’s most powerful mafia. The Good Mothers is the story of the women who broke the silence.",
      },
      {
        // "id": "frSXDwAAQBAJ",
        name: "The Secret Messenger",
        slug: "the-secret-messenger",
        image:"http://books.google.com/books/publisher/content?id=frSXDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE71yXtFcxaj9oba7dsoYfT824fYAkH1xtuWfyMPncQNADdsQuqak1qdR6vlfU3TkR0uJHxCXq-OqAJFOAd9ka-QncNA0J4cBu89W3y42pbtyL-1C6Fg6j6UEdF0q_GfV_wHRp8Zy&source=gbs_api",
        description:
          "The world is at war, and Stella Jilani is leading a double life. By day she works in the lion’s den as a typist for the Reich; by night, she risks her life as a messenger for the Italian resistance. Against all odds, Stella must impart Nazi secrets, smuggle essential supplies and produce an underground newspaper on her beloved typewriter.But when German commander General Breugal becomes suspicious, it seems he will stop at nothing to find the mole, and Stella knows her future could be in jeopardy.",
        price: 4.40,
        countInStock: 4,
        rating: 4,
        numReviews: 3,
      },
      {
        // "id": "kFLEDwAAQBAJ",
        name: "An Irish Country Welcome",
        slug: "an-irish-country-welcome",
        image:"http://books.google.com/books/publisher/content?id=kFLEDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE71w4ZBJgR8r08CkqH7X-iXwluYpswiTwZIjW15H_l4u73go5NspLLUW06khIbWDlPDCPUHMWW2ZAiT1xHrk6SC9AwChPUDgam038GSwifB9RAFKGxhbuYd9H9Eg83G8NwFN6JEa&source=gbs_api",
        description:
          "An Irish Country Welcome is a charming entry in Patrick Taylor's internationally bestselling Irish Country series. In the close-knit Northern Irish village of Ballybucklebo, it’s said that a new baby brings its own welcome. Young doctor Barry Laverty and his wife Sue are anxiously awaiting their first child, but as the community itself prepares to welcome a new decade, the closing months of the 1960s bring more than a televised moon landing to Barry, his friends, his neighbors, and his patients, including a number of sticky questions.",
        price: 8.50,
        countInStock: 10,
        rating: 5,
        numReviews: 3,
      },
      {
        // "id": "vdutwwEACAAJ",
        name: "The Irish Princess",
        slug: "the-irish-princess",
        image:"http://books.google.com/books/content?id=vdutwwEACAAJ&printsec=frontcover&img=1&zoom=5&imgtk=AFLRE72Y4VDOEbMJr9J-ecpfaX6yiHLbZ_nSi9_grczmTslIYnzzPiN-jC5vheJ5VALpdI3sM5HDeALYCjiiOxXr2jso8dahHrRdOlv_P4OL1N-ZOB-llzfiq3yyLqhv_HaofIpgtS_3&source=gbs_api",
        description:
          "The King of Leinster, awaiting news of his newborn child, is disappointed to hear he has a daughter. Diarmait MacMurchada wanted another strapping son to shoulder a spear, wield a sword, and protect his kingdom. But from the moment Diarmait held the newborn Aoife knew she would be his most precious treasure..",
        price: 12.90,
        countInStock: 10,
        rating: 0,
        numReviews: 0,
      },
      {
        // "id": "5kE0EAAAQBAJ",
        name: "Five Tuesdays in Winter",
        slug: "five-tuesdays-in-winter",
        image:"http://books.google.com/books/publisher/content?id=5kE0EAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE72MzemqEAH2enLNZs4Uk64i26FdBouuVz-0kPS7XrDCklk1ZB7nT_-aGtywM3BHophEet9UeRYRLPoiBinvQLnTkK-MufrCw3RB4uXaBdUPgC-oKkBb08NsWpOZHohX_t1906HJ&source=gbs_api",
        description:
          "Told in the intimate voices of unique and endearing characters of all ages, these tales explore desire and heartache, loss and discovery, moments of jolting violence and the inexorable tug toward love at all costs. A bookseller's unspoken love for his employee rises to the surface, a neglected teenage boy finds much-needed nurturing from an unlikely pair of college students hired to housesit, a girl's loss of innocence at the hands of her employer's son becomes a catalyst for strength and confidence, and a proud nonagenarian rages helplessly in his granddaughter's hospital room. Romantic, hopeful, brutally raw, and unsparingly honest, some even slipping into the surreal, these stories are, above all, about King's enduring subject of love.",
        price: 9.40,
        countInStock: 10,
        rating: 0,
        numReviews: 0,
      },
      {
        // "id": "ZfFTAQAAQBAJ",
        name: "Transcending Boundaries",
        slug: "transcending-boundaries",
        image:"http://books.google.com/books/publisher/content?id=ZfFTAQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE72dVJ3TsnPXsFzR8WREVxst3m2BHOW6rdoBEefvWnlBaRb9szFBWdYin5jCRj0TS7VWXD0Iof930OB9S-SKYGx6l9WbRy1r6t9n5Gfp8OucfZt8DPIDuWNOvHUYBU6kMhm0yV2U&source=gbs_api",
        description:
          "Transcending Boundaries: Writing for a Dual Audience of Children and Adults is a collection of essays on twentieth-century authors who cross the borders between adult and children's literature and appeal to both audiences. This collection of fourteen essays by scholars from eight countries constitutes the first book devoted to the art of crosswriting the child and adult in twentieth-century international literature. Sandra Beckett explores the multifaceted nature of crossover literature and the diverse ways in which writers cross the borders to address a dual readership of children and adults.",
        price: 51.20,
        countInStock: 10,
        rating: 3,
        numReviews: 1,
      },
      {
        // "id": "cSdJEAAAQBAJ",
        name: "The Giving Tree",
        slug: "the-giving -tree",
        image:"http://books.google.com/books/publisher/content?id=cSdJEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE71ZGHBpMBO9GwO49nINR2CUWn9o-0NdqB11v-smrPQZh3nrasi-VZVyhvy_1kQ4oJq4lO7Cfy_20BFR2BVmax8KWv4GA98roYliMmvByAM0CpTXXONhccF_9_E7y6_t1xClXWET&source=gbs_api",
        description:
          "The Giving Tree takes you beyond a Christianity that exists only as a title or a good idea and transports you into a living experience with the extraordinary God of the Bible-the One who still does miracles in the lives of ordinary people. Filled with empowering testimonies that touch the heart as well as clear biblical teaching that strengthens the soul, The Giving Tree dares you to believe in a supernatural lifestyle where heaven really breaks forth, Jesus still heals, demons still flee, and God still provides.",
        price: 10.40,
        countInStock: 10,
        rating: 5,
        numReviews: 15,
      },
      {
        // "id": "yqyeBAAAQBAJ",
        name: "A Visit From the Goon Squad",
        slug: "a-visit-from-the-goon-squad",
        image:"http://books.google.com/books/publisher/content?id=yqyeBAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE73ABR7P2g2d51q78EMJo4N4rNORnAKrmomSU6AmHUAhhSuFurn7f2CfskKGe1pHwJ4eclEqpqoKsIL7y2bjb7PEnYktGhf6mT0yftzS6B9QGMlyuS42WJ-0gV_RXGQnbL-3WZR-&source=gbs_api",
        description:
          "Jennifer Egan's spellbinding novel circles the lives of Bennie Salazar, an aging former punk rocker and record executive, and Sasha, the passionate, troubled young woman he employs. Although Bennie and Sasha never discover each other's pasts, the reader does, in intimate detail, along with the secret lives of a host of other characters whose paths intersect with theirs, over many years, in locales as varied as New York, San Francisco, Naples, and Africa.",
        price: 5.40,
        countInStock: 10,
        rating: 5,
        numReviews: 30,
      },
      {
        // "id": "hAv6jJ-eumIC",
        name: "The True Story of Japan's Foremost Geisha",
        slug: "the-true-story-of-japans-foremost-geisha",
        image:"http://books.google.com/books/content?id=hAv6jJ-eumIC&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE734vTsNCS5XRr1lM_zbfJWmXzCErdNkgsKIOSuJpsseIjxtm0PkAlghRDRW0qYCLxW9WMiqmbaE0whu2GTxv1pTgnirEq3qte11MMHXyh6NGomiR0Kw5Bc1ae15E45-SJ2kc1KG&source=gbs_api",
        description:
          "Emerging shyly from her hiding place, Mineko encounters Madam Oima, the formidable proprietress of a prolific geisha house in Gion. Madam Oima is mesmerised by the child's black hair and black eyes: she has found her successor. And so Mineko is gently, but firmly, prised away from her parents to embark on <b>an extraordinary profession</b>, of which she will become the best. But even if you are exquisitely beautiful and the darling of the okiya, the life of a geisha is one of gruelling demands.",
        price: 7.80,
        countInStock: 10,
        rating: 2,
        numReviews: 1,
      },
      {
        // "id": "nhmjYyUjCOsC",,
        name: "Memoirs of a Geisha",
        slug: "memoirs-of-a-geisha",
        image:"http://books.google.com/books/content?id=nhmjYyUjCOsC&printsec=frontcover&img=1&zoom=5&imgtk=AFLRE71YRLuv5LVaEOktQ0_KY6hgd6C0ZzsdMnyNWb4FGtv3d9f7w4NrhpFc8lvKDt3q3369xinsA2XHVrVBF_IxsuZjPPhd4av39saR-dkR3nVRYvZTRwDA8XcwOy9I_dbZNAuoACgW&source=gbs_api",
        description:
          "Memoirs of A Geisha is an epic drama about the remote and shimmeringly exotic world of Sayuri, one of Japan’s most celebrated geishas. The novel has been a beloved bestseller all over the world and is now set to become the major movie event of the year. The film stars Asia’s most celebrated movie stars including Zhang Ziyi (House of Flying Daggers; Hero), Ken Watanabe (The Last Samurai), Gong Li (Raise The Red Lantern), and Michelle Yeoh (Crouching Tiger, Hidden Dragon).",
        price: 9.40,
        countInStock: 10,
        rating: 0,
        numReviews: 0,
      },
      {
        // "id": "FFbCOxkzQ7cC",
        name: "Alice's Adventures in Wonderland",
        slug: "alices-adventures-in-wonderland",
        image:"http://books.google.com/books/content?id=FFbCOxkzQ7cC&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE71Xi_3-okeUVW6MX3cAkRnV3BX_VX_rb41PwMnxul-YVLdNBDrNVHNexVBcnxrgLR8ZVCoh7MFaB9PFOSPRRRNCZEp2D8YMRLy4HRAV1tfsK7RjIneDm3gDm_BQN_UKngFAWHS6&source=gbs_api",
        description:
          "In 1865, English author CHARLES LUTWIDGE DODGSON (1832-1898), aka Lewis Carroll, wrote a fantastical adventure story for the young daughters of a friend. The adventures of Alice-named for one of the little girls to whom the book was dedicated-who journeys down a rabbit hole and into a whimsical underworld realm, instantly struck a chord with the British public, and then with readers around the world. Dodgson's playfulness-with language, with mathematical puzzles, with testy creatures such as the White Rabbit, the Mad Hatter and the Queen of Hearts-still confounds and teases lovers of fantasy fiction today.",
        price: 5.50,
        countInStock: 50,
        rating: 4,
        numReviews: 63,
      },
      {
        // "id": "m2N-DwAAQBAJ",
        name: "Drunk with Love",
        slug: "drunk-with-love",
        image:"http://books.google.com/books/publisher/content?id=m2N-DwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE73FYspXtb_2vt3SDjZPMadzKW8RUNJwlZufBypjYJqFSj7K6hV__Ax91Ak_jrFou7R5OvxQM2UUjf13W2cPKw01hfszyKzoh7GyWzQYUut5_G4xlb7b-aFUZj3xWiathNG49RLL&source=gbs_api",
        description:
          "There is not a single dud in this brilliant collection…crisp stories about marriage, blood, booze and death and the wayward passions fomented by them Time Out From joyous moments to near insurmountable grief, National Book Award-winning author Ellen Gilchrist gives readers vignettes revealing the lives of some of her most memorable characters. In “Traceleen at Dawn,” we see the wealthy Miss Crystal finally give up drinking after a fire consumes her home. In “1941,” readers meet Rhoda Manning, a precocious nine-year-old facing off with the world of adults for the first time. In “The Last Diet,” a woman on a diet crashes her car into a doughnut shop. And murder takes center stage in “Memphis” and “The Emancipator”.",
        price: 9.80,
        countInStock: 10,
        rating: 3.5,
        numReviews: 6,
      },
      {
        // "id": "cfAfEAAAQBAJ",
        name: "Drunk Girl",
        slug: "drunk-girl",
        image:"http://books.google.com/books/publisher/content?id=cfAfEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE73xJixXiB1Va-unD42e21K3JbE4SR5Mpr9CfhY4Db6XnNsjKI2muhVZFBF8z1ZCHrssD03a5G1NBq5Y29Xn4IyxOp7q0I6yxhAirtLebo_ewK2tLMJmfQ5vs1mR3P9TcqeJgiRt&source=gbs_api",
        description:
          "A NEW STANDALONE title from Samantha Lind in her Lyrics and Love series! NICK Beautiful, broken, and abandoned.The second I see her in my bar,With cover charge stamps plastering her hands, I know what I have to do.Take her home,Get her into bed,Where I know she'll be safe. I do exactly that.Leaving her keys and my number, As I lock the door behind me.She deserves more,So much more.ASHLEYShattered, vulnerable, and alone,Trapped in a lifetime of hurt,Trying to break the cycle.But he came in,Saved me,From myself,From my circumstances.Showing me compassion,And respect.Proving I am so much more.More than just a pathetic drunk girl.",
        price: 6.60,
        countInStock: 100,
        rating: 3.4,
        numReviews: 100,
      },
      {
        // "id": "f280CwAAQBAJ",
        name: "Harry Potter: The Complete Collection (1-7)",
        slug: "harry-potter-the-complete-collection",
        image:"http://books.google.com/books/publisher/content?id=f280CwAAQBAJ&printsec=frontcover&img=1&zoom=5&imgtk=AFLRE71tEvw8R3eOVmtZUTpp5Q0KsEA37hd-s_ylm9Cop_C70TdDBiHIlZsm8lkfrtKVpPh0AJTk3nsXxpH3rMNS0MTV7Ydb8xNaZx2HbEWtBFTDhDKdg5DbIJZNCiKRujUNXmb-RSyu&source=gbs_api",
        description:
          "When Harry Potter is left on a doorstep as a baby, he has no idea he is the Boy Who Lived, or that he is famous throughout the wizarding world. Years later, he is astonished to receive an acceptance letter to Hogwarts School of Witchcraft and Wizardry and he is soon whisked off on a magical adventure like no other. Join Harry and his fiercely loyal friends, Hermione and Ron, in this story about the power of truth, love and hope.Having become classics of our time, the Harry Potter eBooks never fail to bring comfort and escapism. With their message of hope, belonging and the enduring power of truth and love, the story of the Boy Who Lived continues to delight generations of new readers.",
        price: 57.90,
        countInStock: 50,
        rating: 5,
        numReviews: 200,
      },
      {
        // "id": "XDn8mI5NPM4C",
        name: "Mageborn",
        slug: "mageborn",
        image:"http://books.google.com/books/content?id=XDn8mI5NPM4C&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE733Yz_Yglkye5I7URw5YD-e-LiNHstJm3g5iZNskjK1pHLhUxWbMARdsFaf6N5sLqlDmbYnQ-w5m30Azwjh5U9PZ4Sl5bAn2qo1_4nqFV5ibACgwjVdttwx1FI-1St0Q4PALydi&source=gbs_api",
        description:
          "Mordecai's simple life as the son of a blacksmith is transformed by the discovery of his magical birthright. As he journeys to understand the power within him he is drawn into a dangerous plot to destroy the Duke of Lancaster and undermine the Kingdom of Lothion. Love and treachery combine to embroil him in events he was never prepared to face. What he uncovers will change his understanding of the past, and alter the future of those around him.",
        price: 3.30,
        countInStock: 10,
        rating: 0,
        numReviews: 0,
      },
      {
        // "id": "yWlnEAAAQBAJ",
        name: "Weather Girl",
        slug: "weather-girl",
        image:"http://books.google.com/books/publisher/content?id=yWlnEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE73s0U1creevwHDy9RWBK6SdglH2wt9Ium42t_sRi4XMcC44q2yH-n7Vx3BjrcFddu5ZMfXqUTbA1KJpzVt_0xhA1eGxBw0H2rWdoQw8OkKEebe_jyzvZLhCC2Ij_ISABZHEfD3y&source=gbs_api",
        description:
          "Ari Abrams loves working as a TV meteorologist. But unfortunately, her boss is so busy fighting with her ex - who happens to be the station's news director - that there's always a storm brewing inside the newsroom!So after a particularly explosive showdown, Ari and shy sports reporter Russell hatch a plan to get their bosses back together, fast . . .As they work to help the sparring exes fall back in love, Ari finds herself telling Russell things that she has always kept hidden - and soon realises there's more to her quiet colleague than meets the eye.It seems like love might have been in front of Ari all along.But will Russell be able to embrace her dark clouds, as well as her clear skies?",
        price: 5.90,
        countInStock: 10,
        rating: 0,
        numReviews: 0,
      },
      {
        // "id": "47W8DwAAQBAJ",
        name: "Beach Read",
        slug: "beach-read",
        image:"http://books.google.com/books/publisher/content?id=47W8DwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE73T5zcThY3AfvawFC1AXe5tQCpkDtKgWrlqxKMpvLiznHP7V71_pKD_LB3frSZrbJEa89Wa-CV6eXBGVANM-bLgZSAoetQViwZU17KsDwmUo9cTTEb4j6IqGmCTpcM7wxl6SRtt&source=gbs_api",
        description:
          "January is a hopeless romantic who narrates her life like she's the lead in a blockbuster movie.<b>Gus is a serious literary type who thinks true love is a fairy-tale.But January and Gus have more in common than you'd think:They're both broke. They've got crippling writer's block. And they need to write bestsellers before summer ends.The result? A bet to swap genres and see who gets published first. The risk? In telling each other's stories, their worlds might be changed entirely...<",
        price: 4.90,
        countInStock: 10,
        rating: 5,
        numReviews: 20,
      },
      {
        // "id": "wcy3Wb27iEEC",
        name: "Leech",
        slug: "leech",
        image:"http://books.google.com/books/content?id=wcy3Wb27iEEC&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE70rnEXyY1f1JjCjoNuXQg4iR7bY7BGRxFS8DHC3TUEOIqNoYFydr-Szm2yN0edOLdCywJgqA7afYEgk3rLUfUOp3DZWDNylFmgjwUTXHIEMonZeV8sthHQCQHMxitdMijTIsjfM&source=gbs_api",
        description:
          "Armed with razor-sharp teeth and capable of drinking many times its volume of blood, the leech is an unlikely cure for ill health. Yet that is exactly the role this worm-like parasite has played in both Western and Eastern medicine throughout history. In this book, Robert G. W. Kirk and Neil Pemberton explore how the leech surfaces in radically different spheres. The ancients used them in humeral medicine to bring the four humors of the body—blood, phlegm, and black and yellow bile—back into balance. Today, leeches are used in plastic and reconstructive surgery to help reattach severed limbs and remove pools of blood before it kills tissue.",
        price: 12.60,
        countInStock: 10,
        rating: 0,
        numReviews: 0,
      },
      {
        // "id": "t_LhCwAAQBAJ",,
        name: "Always Coming Home",
        slug: "always-coming-home",
        image:"http://books.google.com/books/publisher/content?id=t_LhCwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE73SIZlnACBD4fs-FSiMRPg-t7dzoWYk2xOLtOm0pghnUfyXZboX3T5EINOjo4586U9LWxNl415DXzYixNw17eIpZhlSuxpaMKUji07QCiJ6ARk4GBa6_EOuAaeYBtGpfWu_2pqW&source=gbs_api",
        description:
          "A long, long time from now, in the valleys of what will no longer be called Northern California, might be going to have lived a people called the Kesh. But Always Coming Home is not the story of the Kesh. Rather it is the stories of the Kesh - stories, poems, songs, recipes - Always Coming Home is no less than an anthropological account of a community that does not yet exist, a tour de force of imaginative fiction by one of modern literature's great voices.",
        price: 3.40,
        countInStock: 0,
        rating: 0,
        numReviews: 0,
      },
      {
        // "id": "1MXLDwAAQBAJ",
        name: "The Martian",
        slug: "the-martian",
        image:"http://books.google.com/books/publisher/content?id=1MXLDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE71zEGL2d8AjI7W1v_18aDyc2W7r3pHSLWSEV9hxa2mUc9EIJmppcsx76SWmAH_Vsb1g6ziCTyhssC1pGfeK5JP5RrpK8Y-STg5wxBhvUJOHy5gM-LeEeJEdhkfNR3d8ep0f_opM&source=gbs_api",
        description:
          "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he's sure he'll be the first person to die there. After a dust storm nearly kills him and forces his crew to evacuate while thinking him dead, Mark finds himself stranded and completely alone with no way to even signal Earth that he’s alive – and even if he could get word out, his supplies would be gone long before a rescue could arrive. Chances are, though, he won't have time to starve to death. Damaged machinery, the unforgiving environment, or plain old \"human error\" are much more likely to kill him first. But Mark isn't ready to give up yet. Drawing on his ingenuity, his engineering skills and a relentless, dogged refusal to quit, he steadfastly confronts one seemingly insurmountable obstacle after the next. Will his resourcefulness be enough to overcome the impossible odds against him?",
        price: 5.90,
        countInStock: 10,
        rating: 4,
        numReviews: 150,
      },
      {
        // "id": "HmFKEAAAQBAJ",
        name: "Vladimir",
        slug: "vladimir",
        image:"http://books.google.com/books/publisher/content?id=HmFKEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE70LqHb6z9XknrZ02XcpJXg65SpluG9qW_K-VHOfqYNPSVQ8_1uOX1T8f6O8ksTf3B6U4FDS5tZrxoNoTqqFe_AJyY9uLZ3VuQF1pKtF7qStT4IMXDvFPNn9hCOxOIuj4AVGDIL-&source=gbs_api",
        description:
          "a popular English professor whose husband, a charismatic professor at the same small liberal arts college, is under investigation for his inappropriate relationships with his former students. The couple have long had a mutual understanding when it comes to their extramarital pursuits, but with these new allegations, life has become far less comfortable for them both. And when our narrator becomes increasingly infatuated with Vladimir, a celebrated, married young novelist who’s just arrived on campus, their tinder-box world comes dangerously close to exploding. With her bold and edgy literary debut, Julia May Jonas takes us into charged territory, where the restrictions of morality bump up against the impulses of the human heart. Darkly funny and moving, Vladimir maps the personal and political minefield of our current moment, exposing the messy contradictions of power and desire.",
        price: 9.40,
        countInStock: 10,
        rating: 0,
        numReviews: 0,
      },
      {
        // "id": "FzVjBgAAQBAJ",
        name: "The Alchemist",
        slug: "the-alchemist",
        image:"http://books.google.com/books/publisher/content?id=FzVjBgAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE72PLDZuaBbM5FuhddYrTxhbrgEAYwrUVMwt1IUuz3k9Noe33HZWcuwy4wtmQXYRxMLbA9CtmOWcUT1yKoA2gNZW1CPQz17e_DRkoy64JxpOUoPtx8AF6TNEzwo44d1JzI6tyXda&source=gbs_api",
        description:
          " special 25th anniversary edition of the extraordinary international bestseller, including a new Foreword by Paulo Coelho. Combining magic, mysticism, wisdom and wonder into an inspiring tale of self-discovery, The Alchemist has become a modern classic, selling millions of copies around the world and transforming the lives of countless readers across generations. Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined. Santiago's journey teaches us about the essential wisdom of listening to our hearts, of recognizing opportunity and learning to read the omens strewn along life's path, and, most importantly, to follow our dreams.",
        price: 9.40,
        countInStock: 10,
        rating: 0,
        numReviews: 0,
      },
      {
        //  "id": "9ys5EAAAQBAJ",
        name: "Bitter",
        slug: "bitter",
        image:"http://books.google.com/books/publisher/content?id=9ys5EAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE71euGBgu_t8fmPvZVHD9VW9aqLbm2PugkUp25rxZtXTsIUOMtFnsMt9bAUdz9xBJecC8VIU3-cnwt6Ilha-W4BJx3OaJERctgo3wmHhrs5-gySSbJPw_VFCJ-noU-xrm258rjt5&source=gbs_api",
        description:
          "Bitter is thrilled to have been chosen to attend Eucalyptus, a special school where she can focus on her painting surrounded by other creative teens. But outside this haven, the streets are filled with protests against the deep injustices that grip the town of Lucille.Bitter's instinct is to stay safe within the walls of Eucalyptus . . . but her friends aren't willing to settle for a world that the adults say is \"just the way things are.\" Pulled between old friendships, her creative passion, and a new a romance, Bitter isn't sure where she belongs - in the art studio or in the streets. And if she does find a way to help the revolution while being true to who she is, she must also ask: at what cost?",
        price: 7.90,
        countInStock: 0,
        rating: 3,
        numReviews: 0,
      },
      {
        // "id": "wIVKEAAAQBAJ",
        name: "Sedating Elaine",
        slug: "sedating-elaine",
        image:"http://books.google.com/books/publisher/content?id=wIVKEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE72MB4SdkutQ_wYg6Q6gnxLEmCZaVFihqM__CxwtnxEsc23D6SahITFt2o6NsxH0j8OOHDYcxX7_cW-wcMY73jugfmLe1VQY0o-31jz6EwLFMJNvy_2fv55-MMylSWesP1RdyyaQ&source=gbs_api",
        description:
          "An exuberant black comedy about love, grief, sex, guilt, and one woman's harebrained scheme to tranquilize her voraciously amorous girlfriend for a few days so that she might pay off her drug dealer, make soup, and finally get some peace and quiet.</b>Frances was not looking for a relationship when she met Elaine in a bar. She was, in fact, looking to drown her sorrows in a pint or twelve and nurse a broken heart, shattered by the gorgeous, electric Adrienne.",
        price: 3.90,
        countInStock: 50,
        rating: 1,
        numReviews: 1,
      },
      {
        // "id": "ILwrDwAAQBAJ",,
        name: "Girl in Snow",
        slug: "girl-in-snow",
        image:"http://books.google.com/books/publisher/content?id=ILwrDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE70J23owmIbpLgNL2O-xnkeGdLUb0P_jqET8vTQ_yPTwwlyw-roF01fuCKhtOs4aPmmuWzo1gSg5sV1dhpeh75F-SCCjSbsgKK5uVtuOC9kwWKvA0Q3IhbRTaE5Hs3qTjwWU5GKR&source=gbs_api",
        description:
          "When beloved high school student Lucinda Hayes is found murdered, no one in her sleepy Colorado suburb is untouched – not the boy who loved her too much, not the girl who wanted her perfect life, not the police officer assigned to investigate. In the aftermath of the tragedy, these three unforgettable characters – Cameron, Jade, and Russ – must each confront their darkest secrets in an effort to find solace, the truth, or both.",
        price: 5.90,
        countInStock: 10,
        rating: 0,
        numReviews: 0,
      },
      {
        // "id": "EtktDwAAQBAJ",
        name: "A Life Less Throwaway: The lost art of buying for life",
        slug: "a-life-less-throwaway",
        image:"http://books.google.com/books/publisher/content?id=EtktDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE72eO8P1XgLaOBsp7xEb70nnbGcndy6Y__vE5VhC00ZCzt1whu1KLKbyBR4r3CzjSG-ZLJH7lh5h6EKMhjtBjMoUD8VmMLORgzncOmF3Pb9cUYzpA6ju_87ArveNouk1CXnP6plv&source=gbs_api",
        description:
          "Tara Button has become a champion of a lifestyle called ‘mindful curation’ – a way of living in which we carefully choose each object in our lives, making sure we have the best, most classic, most pleasing and longest lasting – kettles, desks, pots & pans, scissors, coats and dresses, instead of surrounding ourselves with throwaway stuff and appliances with built-in obsolescence. ",
        price: 5.10,
        countInStock: 20,
        rating: 0,
        numReviews: 0,
      },
      {
        // "id": "zM8ziVp0SHUC",
        name: "Never Less Than A Lady",
        slug: "never-less-than-a-lady",
        image:"http://books.google.com/books/content?id=zM8ziVp0SHUC&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE71_SO_AIHdKBqAabqu1VS0GxK93othIolfP2_ICF-5G78sTTSyR_E6B-eNeGrv3AK7GPpJR42SZqmeF-329JTNaPvS-s-0rj609qF4hyNYYtaxs5VcosETX25heAuEKU9Kt4QdR&source=gbs_api",
        description:
          "Mary Jo Putney continues her stunning Lost Lords series with this stirring, sensual story of a rebellious nobleman drawn to a lovely widow with a shocking past. As the sole remaining heir to the Earl of Daventry, Alexander Randall knows his duty: find a wife and sire a son of his own. The perfect bride for a man in his position would be a biddable young girl of good breeding. But the woman who haunts his imagination is Julia Bancroft—a village midwife with a dark secret that thrusts her into Randall’s protection.",
        price: 7.40,
        countInStock: 10,
        rating: 0,
        numReviews: 0,
      },
    ],
  
};
export default data;
